services:
  time_sheet_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: time_sheet_app
    volumes:
      - .:/var/www/html:delegated
    networks:
      - time_sheet

  time_sheet_webserver:
    image: nginx:1.23-alpine
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - time_sheet

  time_sheet_mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - time_sheet_mariadb:/var/lib/mysql
    networks:
      - time_sheet

  time_sheet_adminer:
    image: adminer
    ports:
      - "9090:8080"
    depends_on:
      - time_sheet_mariadb
    networks:
      - time_sheet

networks:
  time_sheet:
    driver: bridge

volumes:
  time_sheet_mariadb:
